### ISSUE TITLE
Script for downstream task SemEval 2014 Task 4 finetuning and Eval

### ISSUE THREAD

**Issue by Akhila-Yerukola** [deepopinion/domain-adapted-atsc#2]
Could you please provide the script which was used for Down-stream task-specific (SemEval 2014 Task 4) finetuning?
In the readme, it is mentioned that its an adaptation of [https://github.com/huggingface/pytorch-transformers/blob/v1.0.0/examples/run_glue.py](https://github.com/huggingface/pytorch-transformers/blob/v1.0.0/examples/run_glue.py) .However details of the adaptation are not mentioned. 

Request you to please release your finetuning and evaluation code.

**Comment by xelda1988** [comment]
Hey @Akhila-Yerukola. Thanks for your request. I need to clean the code up a little before pushing it into the repo.

The code is an adaptation in the sense that a new dataprocessor (dataloader) for the semeval task was added. 

It is pretty straight forward to do if you need it immediately.

Best Regards

**Comment by Akhila-Yerukola** [comment]
Hey @xelda1988, Thank you for your response!
Would it be possible to share that dataloader code with me? Or any crude version of the script to finetune on the semeval task that I can work with?

**Comment by xelda1988** [comment]
Sure no problem. I will try to send it to you tomorrow.
