### ISSUE TITLE
Error While executing

### ISSUE THREAD

**Issue by gaurav-bothra** [deepopinion/domain-adapted-atsc#4]
l/cached_train_restaurants_10mio_ep3_128_semeval2014-atsc
Traceback (most recent call last):
  File "run_glue.py", line 475, in <module>
    main()
  File "run_glue.py", line 428, in main
    train_dataset = load_and_cache_examples(args, args.task_name, tokenizer, evaluate=False)
  File "run_glue.py", line 267, in load_and_cache_examples
    all_input_ids = torch.tensor([f.input_ids for f in features], dtype=torch.long)
  File "run_glue.py", line 267, in <listcomp>
    all_input_ids = torch.tensor([f.input_ids for f in features], dtype=torch.long)
AttributeError: 'list' object has no attribute 'input_ids'

**Comment by xelda1988** [comment]
Thanks. 
Looking into it...

**Comment by xelda1988** [comment]
Hey @gaurav-bothra 

I made a fresh install and was able to reproduce your error.
I updated the code and the README section (some packages where also missing in the requirements).

Downstream classification should work now.

Cheers

**Comment by gaurav-bothra** [comment]
Thanks @xelda1988 ,
Let me try!
