### ISSUE TITLE
assert len(tokens_b) >= 1 fail

### ISSUE THREAD

**Issue by fancyerii** [deepopinion/domain-adapted-atsc#6]
When I generate data for pretraining, it failed.

I am using the data file data/transformed/restaurant_corpus_1000000.txt. I found a line with <200d> and it generate an empty sentence.

 231072 Normally I love chipotle, but the Portions are always disappointing and the ingredients never seem very fr        esh.
 231073 My sister hates this location's chicken but love chipotle chicken normally, not sure what they do differen        tly.
 231074 <200d>

**Comment by xelda1988** [comment]
Hi @fancyerii 

This errors should avoided in the latest master branch - did you pull it?

See the following line:

https://github.com/deepopinion/domain-adapted-atsc/blob/1d2d74f010e5e737a05a652fefe80a5bcdc73e58/prepare_restaurant_reviews.py#L58

Do you mean by 200d an unicode character? This should already be fixed.

If its a new character that creates an empty line:
Maybe we have different random seeds, so I never encountered this text before.

You could add the your <200d> string as an in the "replace" functions in the code-line mentioned above.

If you could create a pull request once you fixed the problem that would be awesome...

Hope this helps!

**Comment by fancyerii** [comment]
I have pulled the latest codes. But I haven't rerun prepare_restaurant_reviews.py. I think rereun this script will fix this problem. I simply modify pregenerate_training_data.py to skip when tokens_b is empty.

$ git diff finetuning_and_classification/pregenerate_training_data.py
diff --git a/finetuning_and_classification/pregenerate_training_data.py b/finetuning_and_classification/pregenerate_training_data.py
index ff40d95..4f6f6ee 100644
--- a/finetuning_and_classification/pregenerate_training_data.py
+++ b/finetuning_and_classification/pregenerate_training_data.py
@@ -240,6 +240,10 @@ def create_instances_from_document(
                         tokens_b.extend(current_chunk[j])
                 truncate_seq_pair(tokens_a, tokens_b, max_num_tokens)
 
+                if len(tokens_a) < 1 or len(tokens_b)<1:
+                    print("bug")
+                    continue
+
                 assert len(tokens_a) >= 1
                 assert len(tokens_b) >= 1
