### ISSUE TITLE
Can I refer this repository in my repository?

### ISSUE THREAD

**Issue by yangheng95** [deepopinion/domain-adapted-atsc#7]
It is a great repository. Can I refer to this repository and the corresponding paper in my repository (actually I have referred them in [LCF-ABSA](https://github.com/yangheng95/LCF-ABSA), but forgot to ask for permission)

**Comment by xelda1988** [comment]
Thanks, I'm glad our code is helpful to you.
I hereby give you permission to refer to this repository.
