### ISSUE TITLE
Run experiments with SemEval 2016 Task 5

### ISSUE THREAD

**Issue by azamatolegen** [deepopinion/domain-adapted-atsc#8]
Hello. Great work! Thanks for publishing the code. I am very new to this field and I am trying to reproduce this work with semeval 2016 task 5 for Russian language. Could you please tell me what modifications I should make in order to prepare SemEval2016 Task 5 Russian restaurant Dataset for experiments?

**Comment by xelda1988** [comment]
Hi @azamatolegen 

It seems like there are a couple of subtasks for semeval 2016, this
code here is only for targeted sentiment polarity detection.

I cannot tell you exactly how to do it, 
but I guess it would be straightforward to

1. perform language model finetuning of "bert-multilingual" on domain specific russian text
2. for downstream classification write a dataprocessor to load the semeval 2016 dataformat  like I did https://github.com/deepopinion/domain-adapted-atsc/blob/85afef8a0a1a6179696405db2e33d16adab5efd6/finetuning_and_classification/utils_glue.py#L232

I hope it gave you some quick ideas. 
I find your question a bit too unspecific to discuss it here in more detail. Also this
is a question related to research ideas, which I would rather discuss on email conversation.

So I will close this issue now.
Best regards

**Comment by azamatolegen** [comment]
Thank you for your feedback.

I am now trying to run the code with SemEval 2016 Task 5 Russian
Restaurants.

When I run python run_glue.py I Have following error:

[image: image.png]
 My train.xml looks like that (russian language):
[image: image.png]

I know the question is not related directly to your work. But could you
please help me to figure this out? any help is highly appreciated!
